apiVersion: v1 # Versão da API do Kubernetes
kind: PersistentVolume # Tipo de objeto que estamos criando, no caso um PersistentVolume

metadata: # Informações sobre o objeto
  labels:
    app: traefik
  name: traefik-cert-pv # Nome do nosso PV
  namespace: traefik

spec: # Especificações do nosso PV
  capacity: # Capacidade do PV
    storage: 128Mi #1Gi # 1 Gigabyte de armazenamento
  accessModes: # Modos de acesso ao PV
    - ReadWriteOnce # Modo de acesso ReadWriteOnce, ou seja, o PV pode ser montado como leitura e escrita por um único Nó
  persistentVolumeReclaimPolicy: Retain # Política de reivindicação do PV, ou seja, o PV não será excluído quando o PVC for excluído
  hostPath: # Tipo de armazenamento que vamos utilizar, no caso um hostPath
    path: "/dados/traefikv2/conf/certs" # Caminho do hostPath, do nosso nó, onde o PV será criado
  storageClassName: local-path # Nome da classe de armazenamento que será utilizada
