---
apiVersion: v1
kind: ConfigMap

metadata:
  name: traefik-config
  namespace: traefik
  labels:
    app: traefik

data:
  traefik.toml: |
    [tls.stores]
      [tls.stores.default]
        [tls.stores.default.defaultCertificate]
          certFile = "/data/cert/certificado.crt"
          keyFile  = "/data/cert/certificado.key"

---
